import os
import uuid
import shutil
import csv
import io
import logging
from typing import Optional, List, Dict
from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI, HTTPException, UploadFile, File, Form, BackgroundTasks, Body
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

from src.config.settings import Settings
from src.ai_agent.core.orchestrator import AIAgentOrchestrator
from src.ai_agent.components.database.DBclient import ChromaDBClient
from src.ai_agent.components.tools.agent_tool import (
    initialize_retriever,
    initialize_vision_inference,
    search_food_nutrition_info,
    detect_food_in_image
)

try:
    from src.knowledge.main import run_etl_pipeline
except ImportError:
    def run_etl_pipeline():
        logging.warning("ETL Pipeline module not found. Sync feature disabled.")

settings = Settings()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("NutriBot-API")

global_orchestrator: Optional[AIAgentOrchestrator] = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Manages the lifecycle of the FastAPI application.

    This function handles the initialization of critical components before the API
    starts accepting requests (startup) and cleans up resources when the API shuts down.

    Operations performed on startup:
    1. Creates necessary directories for raw data, annotated images, temporary files, and cache.
    2. Initializes the Vision Inference tool (YOLO) with the specified model path.
    3. Initializes the Semantic Retriever (ChromaDB) with the embedding model.
    4. Initializes the AI Agent Orchestrator (ReAct pattern) with tools and prompt templates.

    Args:
        app (FastAPI): The FastAPI application instance.
    """
    global global_orchestrator
    logger.info("Starting NutriBot API initialization...")

    try:
        root = settings.PROJECT_ROOT
        paths_to_create = [
            os.path.join(root, settings.RAW_DIR),
            os.path.join(root, settings.ANNOTATED_DIR),
            os.path.join(root, settings.TEMP_DIR),
            os.path.join(root, settings.CACHE_DIR)
        ]
        
        for path in paths_to_create:
            os.makedirs(path, exist_ok=True)

        initialize_vision_inference(
            model_path=os.path.join(root, settings.YOLO_MODEL_PATH),
            raw_dir=os.path.join(root, settings.RAW_DIR),
            cache_dir=os.path.join(root, settings.CACHE_DIR),
            annotated_dir=os.path.join(root, settings.ANNOTATED_DIR),
            temp_dir=os.path.join(root, settings.TEMP_DIR)
        )
        logger.info("Vision Inference Initialized")

        db_client = ChromaDBClient(db_path=os.path.join(root, settings.CHROMA_DB_PATH))
        embed_fn = SentenceTransformerEmbeddingFunction(model_name=settings.EMBEDDING_TEXT_MODEL_NAME)
        
        initialize_retriever(
            db_client=db_client,
            collection_name=settings.CHROMA_COLLECTION_NAME,
            embedding_function=embed_fn
        )
        logger.info("Semantic Retriever Initialized")

        prompt_path = os.path.join(root, settings.TEMPLATE_PROMPT_PATH)
        
        global_orchestrator = AIAgentOrchestrator(
            model_name=settings.LLM_MODEL_NAME,
            tools=[search_food_nutrition_info, detect_food_in_image],
            mongo_path=settings.MONGO_CONNECTION_STRING,
            template_prompt_path=prompt_path
        )
        logger.info("AI Orchestrator Ready")

    except Exception as e:
        logger.error(f"Critical Startup Error: {e}")
        raise e

    yield
    
    logger.info("NutriBot API Shutting down...")

app = FastAPI(title="NutriBot API", version="1.0.0", lifespan=lifespan)

class ChatResponse(BaseModel):
    """
    Schema for the chat endpoint response.

    Attributes:
        response (str): The text response generated by the AI agent.
        session_id (str): The unique identifier for the chat session.
    """
    response: str
    session_id: str

class ETLResponse(BaseModel):
    """
    Schema for the ETL trigger endpoint response.

    Attributes:
        status (str): The status of the request (e.g., 'accepted').
        message (str): A human-readable message describing the action taken.
    """
    status: str
    message: str

def _get_raw_csv_path(file_key: str) -> str:
    """
    Resolves the absolute file path for a specific CSV resource key.

    Args:
        file_key (str): The key identifier for the file ('details' or 'nutritions').

    Returns:
        str: The absolute path to the requested CSV file.

    Raises:
        ValueError: If the provided file_key is not recognized.
    """
    root = settings.PROJECT_ROOT
    base_raw_dir = os.path.join(root, "assets", "data", "raw")
    
    mapping = {
        "details": "all_food_details.csv",
        "nutritions": "all_food_nutritions.csv"
    }
    
    if file_key not in mapping:
        raise ValueError("Unknown file key. Use 'details' or 'nutritions'.")
        
    return os.path.join(base_raw_dir, mapping[file_key])

@app.post("/v1/chat", response_model=ChatResponse)
async def chat_endpoint(
    message: Optional[str] = Form(None),
    file: Optional[UploadFile] = File(None),
    session_id: Optional[str] = Form(None)
):
    """
    Processes a chat request from the user, handling both text and image inputs.

    This endpoint acts as the main interface for the AI agent. It manages session
    continuity by using the provided `session_id` or generating a new one. If an
    image is uploaded, it is saved temporarily, and its path is injected into the
    prompt so the AI agent's vision tool can access it.

    Args:
        message (Optional[str]): The user's text query.
        file (Optional[UploadFile]): An image file uploaded by the user for analysis.
        session_id (Optional[str]): The session ID to maintain conversation history. 
                                    If None, a new ID is generated.

    Returns:
        ChatResponse: Contains the AI's response and the active session ID.

    Raises:
        HTTPException (400): If neither message nor file is provided.
        HTTPException (500): If there is an error saving the file or executing the agent.
    """
    if not message and not file:
        raise HTTPException(status_code=400, detail="Please provide either a 'message' or a 'file'.")

    current_session_id = session_id or str(uuid.uuid4())
    logger.info(f"Processing chat for Session: {current_session_id}")

    saved_image_path = None

    if file:
        try:
            temp_dir_full = os.path.join(settings.PROJECT_ROOT, settings.TEMP_DIR)
            clean_filename = f"temp_{current_session_id}_{uuid.uuid4().hex[:6]}_{file.filename.replace(' ', '_')}"
            save_path = os.path.join(temp_dir_full, clean_filename)
            
            with open(save_path, "wb") as buffer:
                shutil.copyfileobj(file.file, buffer)
            
            saved_image_path = save_path
            logger.info(f"Image saved temporarily at: {saved_image_path}")

        except Exception as e:
            logger.error(f"File save error: {e}")
            raise HTTPException(status_code=500, detail="Failed to process uploaded image.")

    user_text = message if message else "Analyze this image and describe the food."
    
    if saved_image_path:
        final_prompt = (
            f"User uploaded an image at this path: {saved_image_path} "
            f"Use the detection tool on that path. "
            f"User request: {user_text}"
        )
    else:
        final_prompt = user_text

    try:
        if not global_orchestrator:
            raise HTTPException(status_code=503, detail="AI Service is not initialized.")

        result = global_orchestrator.invoke(
            session_id=current_session_id,
            user_message=final_prompt
        )
        
        return ChatResponse(
            response=result.get("final_answer", "Sorry, I could not generate a response."),
            session_id=current_session_id
        )

    except Exception as e:
        logger.error(f"Agent Execution Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/v1/download/details")
async def download_details():
    """
    Downloads the 'all_food_details.csv' file from the server's raw data directory.

    Returns:
        FileResponse: The requested CSV file.

    Raises:
        HTTPException (404): If the file does not exist.
        HTTPException (400): If there is an issue resolving the file path.
    """
    try:
        path = _get_raw_csv_path("details")
        if not os.path.exists(path):
            raise HTTPException(status_code=404, detail="Details file not found.")
        return FileResponse(path, media_type="text/csv", filename="all_food_details.csv")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.get("/v1/download/nutritions")
async def download_nutritions():
    """
    Downloads the 'all_food_nutritions.csv' file from the server's raw data directory.

    Returns:
        FileResponse: The requested CSV file.

    Raises:
        HTTPException (404): If the file does not exist.
        HTTPException (400): If there is an issue resolving the file path.
    """
    try:
        path = _get_raw_csv_path("nutritions")
        if not os.path.exists(path):
            raise HTTPException(status_code=404, detail="Nutritions file not found.")
        return FileResponse(path, media_type="text/csv", filename="all_food_nutritions.csv")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/v1/upload/data")
async def upload_data(
    target: str = Form(...),
    file: Optional[UploadFile] = File(None),
    records: Optional[List[Dict]] = Body(None)
):
    """
    Appends new data to the existing CSV datasets (details or nutritions).
    Accepts data either as an uploaded CSV file or a list of JSON records.

    Args:
        target (str): The target file to update ('details' or 'nutritions').
        file (Optional[UploadFile]): A CSV file containing new rows to append.
        records (Optional[List[Dict]]): A JSON body containing a list of records to append.

    Returns:
        JSONResponse: A status message indicating the number of rows appended.

    Raises:
        HTTPException (400): If inputs are invalid (missing data, wrong format, header mismatch).
        HTTPException (500): If filesystem operations fail.
    """
    try:
        target_path = _get_raw_csv_path(target)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid target. Use 'details' or 'nutritions'.")

    if not os.path.exists(os.path.dirname(target_path)):
        raise HTTPException(status_code=500, detail="Target directory configuration error.")

    if not file and not records:
        raise HTTPException(status_code=400, detail="Provide a CSV file or JSON records.")

    try:
        with open(target_path, "r", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            target_header = next(reader)
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to read target CSV header.")

    rows_to_append = []

    if file:
        if not file.filename.lower().endswith(".csv"):
            raise HTTPException(status_code=400, detail="File must be a CSV.")
        
        content = await file.read()
        text = content.decode("utf-8")
        uploaded_io = io.StringIO(text)
        reader = csv.reader(uploaded_io)
        
        try:
            header = next(reader)
            if [h.strip() for h in header] != [h.strip() for h in target_header]:
                raise HTTPException(status_code=400, detail="CSV header mismatch.")
        except StopIteration:
            raise HTTPException(status_code=400, detail="Uploaded CSV is empty.")
            
        for row in reader:
            if any(cell.strip() for cell in row):
                rows_to_append.append(row)

    if records:
        for item in records:
            row = [str(item.get(col, "")) for col in target_header]
            if any(cell.strip() for cell in row):
                rows_to_append.append(row)

    if not rows_to_append:
        return JSONResponse(status_code=200, content={"status": "no_changes", "message": "No new data to append."})

    try:
        with open(target_path, "a", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerows(rows_to_append)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to write data: {e}")

    return JSONResponse(status_code=201, content={"status": "ok", "appended_count": len(rows_to_append)})

@app.post("/v1/admin/sync-knowledge", response_model=ETLResponse)
async def admin_sync_knowledge(background_tasks: BackgroundTasks):
    """
    Triggers the Extract-Transform-Load (ETL) pipeline in the background.

    This process synchronizes the Knowledge Base by reading the CSV data,
    generating embeddings, and updating the ChromaDB vector store.

    Args:
        background_tasks (BackgroundTasks): FastAPI utility for running tasks asynchronously.

    Returns:
        ETLResponse: Confirmation that the task has been accepted.
    """
    background_tasks.add_task(run_etl_pipeline)
    return ETLResponse(status="accepted", message="ETL Pipeline started in background.")

if __name__ == "__main__":
    uvicorn.run("src.api.main:app", host="0.0.0.0", port=8000, reload=True)